// Copyright © 2026 616 Studio LLC. All Rights Reserved. ([https://616.studio](https://616.studio))

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/PlayerController.h"
#include "X_PlayerController.generated.h"

class AX_HUD;
class UX_FloatingDamageTextWidget;
struct FGameplayTag;
class USplineComponent;
class IX_CursorHighlightInterface;
struct FInputActionValue;
class UInputAction;
class UInputMappingContext;

/**
 * <summary>
 * Multicast delegate broadcast on the local client immediately after <c>ClientSetHUD</c> instantiates the HUD.
 * </summary>
 * <remarks>
 * <b>ARCHITECTURE NOTES:</b>
 * <list type="bullet">
 * <item><description>Enables zero-tick, event-driven UI initialization to resolve client replication timing race conditions, where the PlayerState, PlayerController, and HUD replicate down to the client on completely different frames.</description></item>
 * <item><description><b>Documentation:</b>  <a href="https://summer-paradox-663.notion.site/HUD-Initialization-Process-3cbe565e9a8e8017b2a1dad85f6baee1?source=copy_link">HUD Initialization Process</a></description></item>
 * </list>
 * </remarks>
 * <param name="HUDInstance">[<c>AX_HUD*</c>]: Valid pointer to the newly instantiated local HUD actor.</param>
 */
DECLARE_MULTICAST_DELEGATE_OneParam(FOnHUDInitialized, AX_HUD* /* HUDInstance */);

/**
 * <summary>
 * A Top-Down ARPG controller built specifically for GAS.
 * </summary>
 * <remarks>
 * <b>ARCHITECTURE NOTES:</b>
 * <list type="bullet">
 * <item><description><b>GAS Integration:</b> Routes Input Actions mapped to Gameplay Tags to the Player State's ASC for execution of Gameplay Abilities.</description></item>
 * <item><description><b>Contextual Targeting:</b> Manages highlightable actor behavior to determine input context (ex: Attack vs. Move).</description></item>
 * <item><description><b>Navigation & Pathfinding:</b> Uses traditional Top-Down ARPG mouse-click movement, utilizing NavMesh pathfinding and Spline generation for auto-moving.</description></item>
 * </list>
 * </remarks>
 */
UCLASS()
class GAS_AURA_API AX_PlayerController : public APlayerController
{
	GENERATED_BODY()
	
#pragma region  Unreal Defaults
	
public:
	
	AX_PlayerController();
	
	/**
	 * <summary>
	 * Called every frame specifically for Player Controller logic.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Currently only processing the <c>PerformAutoRunning</c> behavior to move the Player along a NavMesh generated <c>SplinePath</c>.</description></item>
	 * </list>
	 * </remarks>
	 */
	virtual void PlayerTick(float DeltaTime) override;
	
protected:
	
	virtual void BeginPlay() override;
	
	virtual void SetupInputComponent() override;
	
private:
	
#pragma endregion Unreal Defaults
	
#pragma region HUD Initialization
	
public:
	
	/** 
	 * <summary>
	 * Broadcasts immediately when the local client HUD is instantiated and assigned. 
	 * </summary>
	 */
	FOnHUDInitialized OnHUDInitializedDelegate;
	
	/**
	 * <summary>
	 * Reliable Server-to-Client RPC initiated server-side by <c>AGameModeBase::InitializeHUDForPlayer()</c> during the player login and pawn initialization sequence.
	 * </summary>
	 */
	virtual void ClientSetHUD_Implementation(TSubclassOf<AHUD> NewHUDClass) override;

protected:
	
private:
	
#pragma endregion HUD Initialization
	
#pragma region Enhanced Input System
	
public:
	
protected:
	
private:
	
	/**
	 * <summary>
	 * Primary IMC.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Currently the only IMC and assigned a default priority of 0.</description></item>
	 * </list>
	 * </remarks>
	 */
	UPROPERTY(EditAnywhere, Category = "***CUSTOM|Input")
	TObjectPtr<UInputMappingContext> IMC_Player;
	
	/**
	 * <summary>
	 * Input Action for 2D directional Character movement along the XY plane.
	 * </summary>
	 */
	UPROPERTY(EditAnywhere, Category = "***CUSTOM|Input")
	TObjectPtr<UInputAction> IA_Move;
	
	/**
	 * <summary>
	 * Handles the actual Character movement.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description><b>Hardware Agnostic:</b> Physical key bindings are defined inside the IMC.</description></item>
	 * <item><description>Cancels any active auto-moving when triggered.</description></item>
	 * </list>
	 * </remarks>
	 * <param name="Value">[<c>FInputActionValue&</c>]: Struct generated by the EIS, expected to contain a processed 2D axis for use with <c>IA_Move</c>.</param>
	 */
	void PerformMove(const FInputActionValue& Value);
	
	/**
	 * <summary>
	 * Helper function that registers the Input Mapping Context(s) with the local Player's Enhanced Input Subsystem.
	 * </summary>
	 */
	void InitInput() const;
	
#pragma endregion Enhanced Input System
	
#pragma region Highlightable Actor Behavior
	
public:
	
protected:
	
private:
	
	/**
	 * <summary>
	 * Performs a raycast from the mouse cursor to detect actors implementing the <c>CursorHighlightInterface</c>.
	 * </summary>
	 */
	void PerformCursorTrace();

	/**
	 * <summary>
	 * Timer handle used to run the cursor trace at a set frequency instead of every frame.
	 * </summary>
	 */
	FTimerHandle CursorTraceTimerHandle;

	/**
	 * <summary>
	 * Used to set how often (in seconds) the cursor trace fires.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Default is 0.05s (20 times a second).</description></item>
	 * </list>
	 * </remarks>
	 */
	UPROPERTY(EditDefaultsOnly, Category = "***CUSTOM|Highlightable Actor Behavior")
	float CursorTraceFrequency = 0.05f;

	/**
	 * <summary>
	 * Caches the highlighted actor from the previous frame.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>By using <c>TWeakInterfacePtr</c>, it prevents a crash if the Actor is destroyed while highlighted.</description></item>
	 * </list>
	 * </remarks>
	 */
	TWeakInterfacePtr<IX_CursorHighlightInterface> PreviousHighlightedActor;
	
	/**
	 * <summary>
	 * Caches the highlighted actor in the current frame.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Besides highlighting behavior, it also determines the <c>bTargeting</c> state for Left Mouse Button logic (deciding whether to attack or move).</description></item>
	 * </list>
	 * </remarks>
	 */
	TWeakInterfacePtr<IX_CursorHighlightInterface> CurrentHighlightedActor;
	
#pragma endregion Highlightable Actor Behavior
	
#pragma region Top-Down RPG Mouse Click Behavior
	
public:
	
protected:
	
private:
	
	/**
	 * <summary>
	 * Automatically moves the Character along the NavMesh generated <c>SplinePath</c> towards the <c>CachedDestination</c>.
	 * </summary>
	 */
	void PerformAutoMove();
	
	/**
	 * <summary>
	 * Checks if the Left Mouse Button is being held down.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>If <c>TRUE</c>, the Player is manually moving the Character, so constantly update the <c>CachedDestination</c> and generate the <c>SplinePath</c>.</description></item>
	 * </list>
	 * </remarks>
	 */
	bool bIsAutoMoving = false;
	
	/**
	 * <summary>
	 * Helper function that configures the mouse cursor to be visible and sets the input mode to Game and UI.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Allows for top-down ARPG-style mouse behavior, ensuring the cursor never locks to the center of the screen.</description></item>
	 * </list>
	 * </remarks>
	 */
	void InitMouseCursor();
	
	/**
	 * <summary>
	 * Represents the exact 3D coordinate the Player clicked on in the game world.
	 * </summary>
	 */
	FVector CachedDestination = FVector::ZeroVector;

	/**
	 * <summary>
	 * Tracks how long the Left Mouse Button has been held down in seconds.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Used alongside the <c>MouseButtonShortPressThreshold</c> to differentiate between a quick click (<c>PerformAutoMove</c>) and a continuous hold (manually moving the Character).</description></item>
	 * </list>
	 * </remarks>
	 */
	float MouseButtonHeldTime = 0.0f;

	/**
	 * <summary>
	 * Allows us to differentiate between holding the mouse button down and simply clicking it and releasing (short press).
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>The 0.5-second cutoff is used to swap between two entirely different movement algorithms.</description></item> 
	 * <item><description>If released <b>BEFORE</b> 0.5 seconds, <c>PerformAutoMove</c> is executed.</description></item>
	 * <item><description>If held <b>AFTER</b> 0.5 seconds, then <c>PerformAutoMove</c> is ignored and the Character continuously steers directly toward the current cursor position.</description></item>
	 * </list>
	 * </remarks>
	 */
	UPROPERTY(EditDefaultsOnly, Category = "***CUSTOM|Top-Down RPG Mouse Click Behavior")
	float MouseButtonShortPressThreshold = 0.5f;

	/**
	 * <summary>
	 * Determines when to stop auto-moving based on how close the Character is to the <c>CachedDestination</c>.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Prevents the Character from "jittering" on top of the exact destination coordinate.</description></item>
	 * </list>
	 * </remarks>
	 */
	UPROPERTY(EditDefaultsOnly, Category = "***CUSTOM|Top-Down RPG Mouse Click Behavior")
	float AutoRunAcceptanceRadius = 50.0f;

	/**
	 * <summary>
	 * The smoothed, curved representation of the NavMesh generated path for the Player's Character to follow.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Unreal's default pathfinding results in Characters traveling in straight lines between points on the path to the destination, including "snapping" rotation behavior when changing direction between points.</description></item>
	 * <item><description>Using a spline allows us to create a curved path to the destination for smoother movement and rotation of the Character.</description></item>
	 * <item><description><b>IMPORTANT:</b> "Allow Client Side Navigation" must be checked (TRUE) in Project Settings - Engine - Navigation System in order for client pathfinding to work.</description></item>
	 * </list>
	 * </remarks>
	 */
	UPROPERTY(VisibleAnywhere)
	TObjectPtr<USplineComponent> SplinePath;

	/**
	 * <summary>
	 * Used to determine if the mouse cursor is hovering over a highlightable actor or not.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>If <c>TRUE</c>, clicking performs an attack.</description></item> 
	 * <item><description>If <c>FALSE</c>, clicking moves the Character.</description></item>
	 * </list>
	 * </remarks>
	 */
	bool bTargeting = false;
	
	/**
	 * <summary>
	 * Locks the intent of the continuous mouse click if it originated on a highlightable actor.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Prevents the Character from suddenly starting to move if the player's cursor slips off the target while holding the attack button.</description></item>
	 * </list>
	 * </remarks>
	 */
	bool bTargetingClickActive = false;

#pragma endregion Top Down RPG Mouse Click Behavior
	
#pragma region Floating Damage Text
	
public:
	
	/**
	 * <summary>
	 * Tells the local client to spawn the floating damage text user widget and project it onto the screen.
	 * </summary>
	 * <remarks>
	 * <b>ARCHITECTURE NOTES:</b>
	 * <list type="bullet">
	 * <item><description>Called locally by the Target Actor's Multicast so the Player Controller can process the UI.</description></item>
	 * </list>
	 * </remarks>
	 */
	UFUNCTION()
	void ShowFloatingDamageText_Local(const float DamageAmount, const FVector TargetLocation, const AActor* InstigatorActor, const FGameplayTag MessageTag, const FGameplayTag AbilityTag);
	
protected:
	
	/**
	 * <summary>
	 * The class used to spawn the user widget responsible for the floating damage text.
	 * </summary>
	 */
	UPROPERTY(EditDefaultsOnly, Category = "***CUSTOM|UI")
	TSubclassOf<UX_FloatingDamageTextWidget> FloatingDamageTextWidgetClass;
	
private:
	
#pragma endregion Floating Damage Text

};